### ISSUE TITLE
Link issue with theplayers page

### ISSUE THREAD

**Issue by BlakeHancockPGAT** [hlxsites/pga-tour-issues#21]
Hi All,

We are seeing an issue with [The Players page](https://www.theplayers.com/charity/info/red-coat-grants ). The link to [CLICK HERE TO VIEW THE CHARITY GUIDELINES](https://www.theplayers.com/content/dam/the-players/charity/2022/22pla-grants-guidelines-081622-v2.pdf) 

is throwing a 404. I assume that since the page moved from AEM the filepath is no longer valid. 

We added the file to our main pgatour website to link to - https://www.pgatour.com/content/dam/pgatour/tournament-sites/pga-tour/r011/charity/22pla-grants-guidelines-081622-v2.pdf and updated the word document https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BF13ECD4F-C6AE-4EB0-AECC-97C8D0627744%7D&file=red-coat-grants.docx&action=default&mobileredirect=true

and published the changes but the link doesn't seem to be updating on the front end. 
<img width="820" alt="image" src="https://user-images.githubusercontent.com/114704520/193156555-3f6900c5-95aa-4398-8aef-3de5d7e621e1.png">

A few questions as well from this issue. What is best practice for this scenario? Will PDFs be uploaded to the sharepoint and can they be used to link to PDFs on the front end? 

Thanks,
Blake Hancock

**Comment by davidnuescheler** [comment]
the PDFs can be uploaded to sharepoint and previewed / published from there. as you have now already added the PDF to the main pgatour site which is of course a good solution as well, i added a redirect just to make sure that any inbound links would remain working.

**Comment by ezaleski2** [comment]
Hi David - thanks for taking care of this instance. I had to manually put that pdf in a different location on the main pgatour site (since it lived under the players DAM which was decommissioned), so I don't think that redirect will cover other areas of the new franklin site that may have had links to pdfs. What would be the best option for identifying other broken links that now exist on the site because of this?

Moving forward, it makes sense to house all docs in the new players sharepoint. This was my initial plan before I tried doing the above workaround above. However, I received the following message (attached screenshot) when trying to make this document public. Is there a different location to place these files, or do we need to have some permissions adjusted? 

https://adobe.sharepoint.com/sites/HelixProjects/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FHelixProjects%2FShared%20Documents%2Fsites%2Fpga%2Dtour%2Ftheplayers%2Dcom%2Fassets%2F2022%2F09&viewid=124ad5f1%2D60ba%2D476c%2Dade8%2D7c1df274ee95 

![2022-09-30 10_26_31-HelixProjects - 09 - All Documents](https://user-images.githubusercontent.com/111150826/193293720-b75b75ec-20b9-40a9-824d-cc4c9d8ef269.png)

**Comment by davidnuescheler** [comment]
understood... 

it seems that there are no other broken links on the site, at least that's what i can see from the https://www.deadlinkchecker.com/ 

i am not 100% clear about the above screenshot but i published the `.pdf` you uploaded into sharepoint. https://www.theplayers.com/assets/2022/09/22pla-grants-guidelines-081622-v2.pdf

we are still considering a couple of options on how to expose the publishing of PDFs from sharepoint, so please feel free let us know if you have additional PDFs that you would like published, and we can very easily take care of that.

**Comment by ezaleski2** [comment]
Thanks David - I figured out what I was doing wrong. After opening the file in sharepoint, I realized I had to click "Open" then "Open in browser" in order to get the helix bar to work as expected. 

In my last post, I was just opening the file and trying to make it public.

I don't have any other files at the moment, so I think we're good to close and go this route moving forward. Thanks!

Ed
